title: Ardi Nusawan Blog
email: ardi.nusawan13@gmail.com
description: Personal blog of I Dewa Putu Ardi Nusawan
baseurl: ""
url: ""
twitter_username: ardinusawan
github_username: ardinusawan
google_analytics: UA-137828798-1
paginate: 10
permalink: /blog/:year/:month/:day/:title
paginate_path: "/blog/page:num/"

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
