title: Ardi Nusawan Blog
email: ardi.nusawan13@gmail.com
description: Personal blog of I Dewa Putu Ardi Nusawan
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ardinusawan
github_username: ardinusawan
google_analytics: UA-137828798-1
comments: true

# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: ardinusawan

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

permalink: /blog/:year/:month/:day/:title
